### ISSUE TITLE
Add E2E test to python-base

### ISSUE THREAD

**Issue by mitar** [kubernetes-client/python-base#117]
Instead of mocked API. To really test if things work. There is now [kind](https://github.com/kubernetes-sigs/kind) which can help setup a Kubernetes cluster inside a CI against which then to test.

**Comment by micw523** [comment]
It's finally arrived for k8s 1.11+...

Yet we've set up the environment for the main repo. It's using minikube inside the CI to run the tests under e2e_test. If you want to make sure it works, you could potentially put some tests there.

**Comment by roycaihw** [comment]
we have e2e env set up in the [main repo](https://github.com/kubernetes-client/python/tree/master/kubernetes/e2e_test) and we do run [all tests from both repos](https://github.com/kubernetes-client/python-base/blob/c4de8bdf404c442389d2a0c421d6f99d80ab1d3a/run_tox.sh#L36-L53) in python-base CI (e.g. search for "e2e" [here](https://travis-ci.org/kubernetes-client/python-base/jobs/506441394))

I think we could add e2e tests in base repo without extra env change. Question is how we manage [dependency](https://github.com/kubernetes-client/python/blob/fcda6fe96beb21cd05522c17f7f08c5a7c0e3dc3/kubernetes/e2e_test/test_client.py#L20-L24) and [packaging](https://github.com/kubernetes-client/python/issues/229) for the tests

**Comment by roycaihw** [comment]
on the other hand we can improve https://github.com/kubernetes-client/python/blob/master/kubernetes/e2e_test/test_client.py to test watch/follow behavior after https://github.com/kubernetes-client/python-base/pull/93 is included in the main repo

**Comment by micw523** [comment]
If we add e2e tests to the main repo, we'll need to potentially merge a feature / bug fix PR to the base repo first, then check in the base repo commit and the e2e test into the main repo at the same time. It's kind of a pain but it's not impossible.

On the other hand, if we set up e2e in the base repo, we should be fine with the dependencies since the CI are run from the main repo but we do need to tune CI testing. If somebody takes #118 some of the obstacles should be cleared out of the way.

**Comment by roycaihw** [comment]
I think https://github.com/kubernetes-client/python-base/issues/117#issuecomment-473100144 and https://github.com/kubernetes-client/python-base/issues/117#issuecomment-476335504 still hold. The problem is in python-base developer UX. Developers should be able to add E2E tests in the same PR as their add new features / fix bugs. 

Two naive ways of fixing this: 
- just port some e2e tests from the main repo to the base repo and verify if they work. If so, it can be the starting point of adding more e2e tests to python-base
- merge python and python-base into one repo

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
