### ISSUE TITLE
Port test pipelines from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by palnabarun** [kubernetes-client/python-base#249]
The `kubernetes-client/python` has moved most of the test pipelines from Travis CI to GitHub Actions. (https://github.com/kubernetes-client/python/issues/1257)

The end goal eventually is to move everything to Prow, but for now, a low hanging fruit is to move out of Travis CI.

**Comment by palnabarun** [comment]
Initial Setup in kubernetes-client/python: https://github.com/kubernetes-client/python/pull/1166
Moving e2e workflows: https://github.com/kubernetes-client/python/pull/1286

**Comment by roycaihw** [comment]
@palnabarun Do you plan to work on this or do you need help?

**Comment by KuberDriver** [comment]
Apologies for the delayed action on this!
Current update: Made changes in forked repo and testing Test run CI with GitHub Actions [here](https://github.com/KuberDriver/python-base/actions). Few tests are failing due to kube-init.sh from kubernetes/python repo mostly aligned to run on travis only. Testing fix to run them successfully in GH Actions. Will submit PR as soon as possible.

**Comment by KuberDriver** [comment]
2 PRs in place to achieve the port from travis CI to GitHub actions. 

For kubernetes/python-base: https://github.com/kubernetes-client/python-base/pull/273
For kubernetes/python: https://github.com/kubernetes-client/python/pull/1659

Tests carried out as part of feature branch CI runs, below are key notes:
- Python version 3.5 is not supported in GH agents hence related test matrix is not configured
- While python 3.6 to 3.9 are passing 3.x(6..9)-functional tests are failing due to underlying tests needing updates (could open new issue for same)

@palnabarun Can you please review above and suggest any changes?

**Comment by roycaihw** [comment]
This repo has been merged into the main [python repo](https://github.com/kubernetes-client/python). We are archiving this repo. Please open a new issue in the main repo. Thanks!

/close
