### ISSUE TITLE
stream/ws_client.py doesn't close the connection if _preload_content is True

### ISSUE THREAD

**Issue by saurabh-chordiya** [kubernetes-client/python-base#53]
Using kubernetes-4.0.0 python client and exec call as below:-

stream( api.connect_get_namespaced_pod_exec,                                                        
            name=pod_name, namespace=namespace, command=cmd,                                                         
            stderr=True, stdin=False, stdout=True, tty=False)

After this call it returns output as a string and not closing connection so If I use it in scale env then I see below error:-
filedescriptor out of range in select

So IMO ws_client.py should be fixed from below code snippet to close connection before return:-
        client.run_forever(timeout=_request_timeout)
        return WSResponse('%s' % ''.join(client.read_all()))

Please fix this if my observation is correct here.

**Comment by saurabh-chordiya** [comment]
@mbohlool

**Comment by bboe** [comment]
Here's a simple example that demonstrates the problem generically with select:

```python
#!/usr/bin/env python3
import select
import sys


def main():
    file_objects = []
    # Show that 1023 is okay.
    while not file_objects or file_objects[-1].fileno() < 1024:
        file_objects.append(open('/dev/null'))

    # FD 1023 works
    print(select.select((file_objects[-2],), (), ()))
    # FD 1024 does not
    print(select.select((file_objects[-1],), (), ()))


if __name__ == "__main__":
    sys.exit(main())
```

I verified that on both OS X and Linux the following exception occurs:

```
Traceback (most recent call last):
  File "./select_demo.py", line 19, in <module>
    sys.exit(main())
  File "./select_demo.py", line 15, in main
    print(select.select((file_objects[-1],), (), ()))
ValueError: filedescriptor out of range in select()
```

I'm going to work on a hopefully simple PR to change from select to poll as I just started running into this issue when using this library within a flask application that supports thousands of threads.

**Comment by bboe** [comment]
Just to add to the above, the root issue is with whatever the file descriptor number is that [is being selected on](https://github.com/kubernetes-client/python-base/blob/1d5231cee6d0674b958ad429b60dda39363a4dc1/stream/ws_client.py#L174). In my case, this is due to external open files, but for you it could be due to the reason you've described. Either way, using select seems like a non-ideal way to go.

**Comment by PaulFurtado** [comment]
@bboe it's not actually the file descriptor number being selected on, but the ulimit on the total count. The default ulimit for open files is 1024. File descriptor numbers are per-process, but ulimits account for all processes running as a given user.

It doesn't matter which socket polling method you use, you'll still have just as many file descriptors total. To scale to thousands of file descriptors, you'll need to just adjust the ulimits on the process.

That said, a single select statement also cannot poll more than 1024 file descriptors either, however in the example above you only poll one descriptor at a time so that doesn't matter. But if you do need one statement to watch more than 1024 file descriptors, you'd want to switch to epoll or run select on multiple threads.

**Comment by bboe** [comment]
@PaulFurtado it is actually the file descriptor being selected on. Here's an example showing a single file descriptor selection failing:

```
#!/usr/bin/env python3
import select
import sys


def do_select():
    file_objects = []
    while not file_objects or file_objects[-1].fileno() < 1024:
        file_objects.append(open('/dev/null'))

    # FD 1023 works
    print(select.select((file_objects[-2],), (), ()))
    # FD 1024 does not
    print(select.select((file_objects[-1],), (), ()))


def do_poll():
    file_objects = []
    while not file_objects or file_objects[-1].fileno() < 1024:
        file_objects.append(open('/dev/null'))

    poll = select.poll()
    poll.register(file_objects[-1], select.POLLIN | select.POLLOUT)
    print(poll.poll())


def main():
    do_poll()
    print('poll works')

    do_select()

if __name__ == "__main__":
    sys.exit(main())
```
